package com.example.demo.parser;

import java.util.HashMap;
import java.util.Map;

import org.springframework.stereotype.Component;

@Component
public class keyPositions {
	private Map<String,String[]> map;
	public keyPositions() {
		map=new HashMap<String,String[]>();
		map.put("managers",new String[] {"managers","project manager","team manager","juniour manager","senior manager","marketing manager","account manager","operations manager","human resource manager","assistant manager","manager","management"});
		map.put("leaders",new String[] {"leaders","project leader","team leader","technical leader","team lead operations","team lead human resources","team lead","human resources"});
		map.put("senior executive",new String[] {"senior executive","senior executive-administrative services","senior executive-it compliance","senior corporate communication executive","senior executive accounts","technical support senior executive","program executive","senior executive-human resources","senior executive- finance","management","executive"});
		map.put("re-engineering",new String[] {"re-engineering team","re engineering","business process re-engineering","robotics process automation","business process re-engineering professional","bpr advisory","bpr manager","bpr support manager"});
		map.put("systems engineer",new String[] {"systems engineer","hardware systems engineer","software systems engineer","senior systems engineer","it systems engineer","windows system engineer","network system engineer","technical support engineer","cloud system engineer","senior r & d systems engineer","infra network system engineer"});
		map.put("systems analyst",new String[] {"systems analyst","systems analyst-application solutions","system analyst-implementation","business system analyst","senior system analyst","java system analyst","application system analyst","production operations analyst","system support analyst","junior system analyst","lead system analyst","senior it network analyst","ita"});
		map.put("systems architect",new String[] {"systems architect","juniour systems architect","senior systems architect","systems architect architect engineer","chief systems architect","lead systems architect","communications systems architect","info systems architects","application architect","software architect","r & d system architect","warehouse management system architecture"});
		map.put("information security",new String[] {"information security","local information security officer","information security consultant","it security architect","it security engineer","it security manager","cybersecurity analyst","it security analyst","information security program analyst","information security risk assessment"});
		map.put("enterprise architect",new String[] {"enterprise architect","java enterprise architect",".net enterprise architect","enterprise solutuion architect","pre sales enterprise architect","enterprise architect -cloud and virtualisation","lead enterprise architect","network enterprise architect","regional enterprise architect","it services-enterprise architect","staff enterprise architect","digital enterprise architect","cloud enterprise architect","enterprise infrastructure services architect"});
		map.put("security administrator",new String[] {"security administrator","system security administrator","network security administrator","it security administrator","information security administrator","access control administartor","admin executive","it security analyst"});
		map.put("security engineer",new String[] {"security engineer","principal security engineer","application security engineer","cloud security engineer","information security engineer","cybersecurity engineer","it security engineer","associate security engineer","hardware security engineer","infra security engineer","juniour security engineer","senior security engineer"});
		map.put("security architect",new String[] {"security architect","senior cyber security architect","security solution architect manager","information security architect","senior information security architect","lead it security architect","it security architect","cloud security architect","cyber security architect","mobile security architect","infrastructure security architect"});
		map.put("security specialist",new String[] {"security specialist","it security specialist","application security specialist","information technology security specialist","security specialist consultant","lead it security specialist","senior it security specialist","senior security specialist","cyber security specialist","senior information security specialist","juniour secuirty specialist","network security specialist","cloud security specialist"});
		map.put("security manager",new String[] {"security manager","it security manager","infra security manager","information security manager","application security manager","regional security manager","it security senior manager","safety and security manager","operational technology security manager","security assistant manager","cyber security manager","network security manager"});
		map.put("security analyst",new String[] {"security analyst","cyber security analyst","it security analyst","information security analyst","senior security analyst","network security analyst"});
		map.put("risk manager",new String[] {"risk manager","technology risk manager","market risk manager","enterprise risk manager","business risk manager","operations risk managers","senior risk manager","juniour risk manager","third party risk manager","credit risk manager"});
		map.put("cyber security professional",new String[] {"cyber security professional","cyber security penetration tester","principal security engineer","application security consultant","cybersecurity competency developer","cybersecurity professional officer","cyber security senior consultant","cybersecurity associate trainer","cybersecurity operations engineer","security"});
		map.put("senior manager",new String[] {"senior manager","operations senior manager","administration senior manager","associate senior manager","senior manager -facilities management","research senior manager","consulting senior manager","senior manager-space management","iot and ai senior manager","senior manager-service management"});
		map.put("c suite executive",new String[] {"c suite executive","executive assistant to c-suite","innovation executive","c-suite"});
		map.put("governance managers",new String[] {"governance managers","group governance manager","data governance manager","vendor contract governance manager","network security governance manager","it governance manager","financial market governance manager"});
		map.put("compliance managers",new String[] {"compliance managers","product compliance manager","advisory compliance manager","corporate banking compliance manager","fintech complaince manager","senior complaince manager","regional business compliance manager","compliance officer","compliance assistant manager","insurance compliance manager","regulatory compliance manager","regional trade compliance manager"});
		map.put("enterprise system owners",new String[] {"enterprise system owners","business system analyst","it associate analyst","enterprise system solution architect"});
		map.put("data owners",new String[] {"data owners","head of data governance","data governance manager","data management lead","data manager","data management analyst","data product owner","head of data products","big data consultants","senior data scientist","data science manager","data advisory lead"});
		map.put("solution architecture",new String[] {"solution architecture","solution architect",".net solution architect","senior solution architect","solution architect-functional specialist","technical solutions architecture","principal solution architect","it solution architect","aws solution architect","security solution architect manager","lead solution architect","cloud solution architect","salesforce solution architect","hosting solution architect","architect"});
		map.put("data scientist",new String[] {"data scientist","data strategist","data analytics","senior data scientist","ai/ml data scientist","business analytics","data scientist nlp","lead data scientist","data scientist-computer vision","full stack data scientist","chief data scientist","principal data scientist","data science","ai","ml","artificial intelligence","machine learning"});
		map.put("data analyst",new String[] {"data analyst","business data analyst","hr data analyst","senior data analyst","data analyst-sql","global retail data anlyst","pricing reference data analyst","data engineer","data analyst- specialist","senior data analyst","investment data analyst","juniour mid level data analyst","business intelligence data analyst"});
		map.put("network developer",new String[] {"network developer","mobile developer","software developer","network designer","network software engineer","software and application developer","network engineer","senior security developer","staff network engineer","software defined networking engineer","juniour sharepoint developer","software engineer","network specialist"});
		map.put("marketing",new String[] {"marketing","marketing director","marketing executive","digital marketing manager","digital marketing executive","product marketing manager","performance marketing specialist","brand marketing","regional channel marketing executive","global marketing manager","trade marketing manager","digital marketing associate"});
		map.put("software professional",new String[] {"software professional","software developer","senior professional software engineer","embedded software professional","senior software engineer","front end developer","back end developer","java software engineers","developer lead","programmer","program anlyst","senior program analyst","software engineer","it professional","software","developer","support","debug","dba"});
		map.put("network architect",new String[] {"network architect","principal network archhitecture","network infrastructure engineer","senior network engineer","senior network technical architect","network enterprise architect","regional telecom network architect","senior infrastructure network architect","cloud native networking architect ","cybersecurity network architect","network solution architect","network security enginner","juniour network engineer"});
		map.put("software architect",new String[] {"software architect","senior software architect","java software architect",".net software architect","software solution architect","digital software architect","lead software architect","principal software architect","application architect","machine learning-solutions architect","application platform architect"});
		map.put("software administration",new String[] {"software administration","it projects administartor","software duplication administration","sas administrator","juniour it system administrator","software engineer-database administrator","systems administrator","big data system administrator","middleware system administrator","database administrator","it administrator"});
		map.put("software engineer",new String[] {"software engineer","software engineer-digital platforms","senior php software engineers","lead software engineer","senior software engineer","software engineering manager","software engineer-mobile app","senior software engineer java ","senior software developer","software engineer-front end","software engineer back end","computer engineer","systems engineer"});
		map.put("software designer",new String[] {"software designer","software engineer digital platforms","software engineer","software programmer","software developer","senior software developer","senior kernel software developer","software architect","architect"});
		map.put("software developer",new String[] {"software developer","software engineer","senior web software developer","front end software developer","senior software developer","datawarehouse senior developer","android mobile platforms","developer"});
		map.put("software analysts",new String[] {"software analysts","software engineer analyst","software testing analyst","it software analyst","system analyst","analyst programmer","software development analyst","principal analyst developer","technical analyst","senior application analyst and designer","software support analyst","technical business analyst","principal analyst developer","software quality analyst"});
		map.put("software manager",new String[] {"software manager","test manager","software test manager","senior software manager","software technical manager","software technical lead","devops manager","project manager","software development manager","manager"});
		map.put("qa manager",new String[] {"qa manager","it quality assurance manager","assistant qa manager ","qa lead","qa supervisor","qa operation specialist","qa administrator"});
		map.put("qa tester",new String[] {"qa tester","software qa tester","javascript qa tester","lead qa tester","senior test analyst","qa test engineer","software qa specialist","qa automation engineer","performance tester","senior software tester","selenium"});
		map.put("penetration tester",new String[] {"penetration tester","cybersecurity penetartion tester","penetration tester - security consultant","senior penetration tester","cybersecurity penetartion test specialist","application penetration tester","mobile penetration tester","penetration test researcher","hacker"});
		map.put("project manager",new String[] {"project manager","technical project manager","project manager-vendor management","cloud project manager","agile project manager","senior project manager","senior it project manager","business project manager","it project manager","java project manager",".net project manager","finance project manager"});
		map.put("project stakeholders",new String[] {"project stakeholders","project manager","project governance","procurement partner","project management coordinator","project management professional","strategy enablement specialist","project administrator"});
		map.put("product manager",new String[] {"product manager","product manager-experience centre","lead product manager","senior product manager","tech product manager","senior investment product amanger","technical product manager"});
		map.put("technology strategist",new String [] {"technology strategist","senior associate technology strategist","innovation content startegist","cloud security strategist","senior media planning strategist","digital strategist","brand strategist","solution architect strategist","partner technology strategist","security and compliance strategist","design strategist","data strategist"});
		map.put("cio",new String[] {"cio","cio-finance","chief digital information officer","information technology director"});
		map.put("Digital professional",new String[] {"digital professional","senior digital marketing professionals","online marketing executives","digital project manager","digital trust associate","digital finance manager","digital finance associate director","digital"});
		map.put("cto",new String[] {"cto","chief technologist"});
		map.put("corporate planner",new String[] {"corporate planner","senior manager-corporate planning","assistant corporate palnning manager","strategy and corporate planning analyst"});
		map.put("business unit managers",new String[] {"business unit managers","unit manager","enterprise intelligence business unit managers","business unit coordinator","business unit head","business unit director","cluster manager","business unit specialist","it business partner"});
		map.put("social media admin",new String[] {"social media admin","social media group admin","social media page admin"});
		map.put("business professional", new String[] {"business professional"});
		map.put("digital leader",new String[] {"technology strategist","senior associate technology strategist","innovation content startegist","cloud security strategist","senior media planning strategist","digital strategist","brand strategist","solution architect strategist","partner technology strategist","security and compliance strategist","design strategist","data strategist"});
		map.put("it support",new String[] {"it support","it support executive","it support engineer","it support specialist","juniour it support","it production support","it support analyst","technical support engineer","senior it support analyst","support"});
		map.put("it manager",new String[] {"it manager","it senior manager","assistant it manager","regional it manager","infra and it security manager"});
		map.put("it professional",new String[] {"it professional","system analyst","it professional services engineer","software developer","software consultant","senior software consultant","web developer","database administrator","senior it engineer","mobile developer","front end developer","back end developer","qa autoamtion engineer","java developer","sap consultant","network operations center"});
		map.put("it architect",new String[] {"it architect","it architect head","solution architect","application architect","senior solution architect","enterprise architect","lead solution architect","cloud delivery architect","senior software architect","enterprise cloud architect","senior process architect","lead enterprise architect",".net solution architect","technical solution architect"});
		map.put("it designer",new String[] {"it designer","senior graphics designer","ux designer","solution designer","service designer","web designer"," product designer","application designer","lead user experience designer","senior front end developer"});
		map.put("it executor",new String[] {"it executor"});
		map.put("it developer",new String[] {"it developer","senior it developer","java developer","javascript developer","it developemnt officer","web developer","software engineer","senior software developer",".net developer","it"});
		map.put("app Developer",new String[] {"app developer","android app developer","ios app developer","hybrid mobile application developer","developer"});
		map.put("team leader",new String[] {"team leader","team lead","it team lead","senior team lead","recruitment team lead","team lead-order fulfillment","infrastructure team leader","sales team lead","network team lead","professional team lead","product support lead","cloud tech lead"});
		map.put("service managers",new String[] {"service managers","it service manager","senior service manager","customer service manager","infrastructure defense service manager","itsm service manager","client service manager","branch sales and service manager"});
		map.put("marketing executives",new String[] {"marketing executives","digital marketing executive","sales and marketing executive","events and marketing executive","product marketing executive","juniour digital marketing executive","social and content marketing executive","senior marketing executive"});
		map.put("marketing analyst",new String[] {"marketing analyst","marketing associate analyst","digital marketing analyst","product marketing analyst","senior marketing analyst","business analyst","product marketing executive","content marketing analyst","market research analyst","regional marketing analyst"});
		map.put("marketing managers",new String[] {"marketing managers","financial products  maarketing manager","digital marketing manager","product marketing manager","consumer marketing manager","assistant marketing manager","senior marketing manager","global marketing manager","growth and performance marketing manager","regional product marketing manager"});
		map.put("quality and process improvement managers",new String[] {"quality and process improvement managers","continuous improvement manager","continuous improvement senior manager","network quality and improvement manager","assistant quality manager","process improvement lead","process improvement specialist","quality distribution manager","process and performance manager","continuous improvement lead engineer","process improvement leader","qa"});
		map.put("innovation managers",new String[] {"innovation managers","open innovation manager","senior manager innovation lead","digital innovation manager","customer experience and innovation manager","product development innovation and technology","innovation"});
		}
	
	public HashMap<String,String[]> getMap(){
		return (HashMap<String, String[]>)map;
	}
}
